version: "3"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/Chinook.sql:/docker-entrypoint-initdb.d/Chinook.sql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
