// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArtist = "Artist"

// Artist mapped from table <Artist>
type Artist struct {
	ArtistID int32  `gorm:"column:ArtistId;primaryKey;autoIncrement:true" json:"ArtistId"`
	Name     string `gorm:"column:Name" json:"Name"`
}

// TableName Artist's table name
func (*Artist) TableName() string {
	return TableNameArtist
}
