// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMediaType = "MediaType"

// MediaType mapped from table <MediaType>
type MediaType struct {
	MediaTypeID int32  `gorm:"column:MediaTypeId;primaryKey;autoIncrement:true" json:"MediaTypeId"`
	Name        string `gorm:"column:Name" json:"Name"`
}

// TableName MediaType's table name
func (*MediaType) TableName() string {
	return TableNameMediaType
}
