// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlaylistTrack = "PlaylistTrack"

// PlaylistTrack mapped from table <PlaylistTrack>
type PlaylistTrack struct {
	PlaylistID int32 `gorm:"column:PlaylistId;primaryKey" json:"PlaylistId"`
	TrackID    int32 `gorm:"column:TrackId;primaryKey" json:"TrackId"`
}

// TableName PlaylistTrack's table name
func (*PlaylistTrack) TableName() string {
	return TableNamePlaylistTrack
}
