// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlaylist = "Playlist"

// Playlist mapped from table <Playlist>
type Playlist struct {
	PlaylistID int32  `gorm:"column:PlaylistId;primaryKey;autoIncrement:true" json:"PlaylistId"`
	Name       string `gorm:"column:Name" json:"Name"`
}

// TableName Playlist's table name
func (*Playlist) TableName() string {
	return TableNamePlaylist
}
