// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlbum = "Album"

// Album mapped from table <Album>
type Album struct {
	AlbumID  int32  `gorm:"column:AlbumId;primaryKey;autoIncrement:true" json:"AlbumId"`
	Title    string `gorm:"column:Title;not null" json:"Title"`
	ArtistID int32  `gorm:"column:ArtistId;not null" json:"ArtistId"`
}

// TableName Album's table name
func (*Album) TableName() string {
	return TableNameAlbum
}
