// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInvoiceLine = "InvoiceLine"

// InvoiceLine mapped from table <InvoiceLine>
type InvoiceLine struct {
	InvoiceLineID int32   `gorm:"column:InvoiceLineId;primaryKey;autoIncrement:true" json:"InvoiceLineId"`
	InvoiceID     int32   `gorm:"column:InvoiceId;not null" json:"InvoiceId"`
	TrackID       int32   `gorm:"column:TrackId;not null" json:"TrackId"`
	UnitPrice     float64 `gorm:"column:UnitPrice;not null" json:"UnitPrice"`
	Quantity      int32   `gorm:"column:Quantity;not null" json:"Quantity"`
}

// TableName InvoiceLine's table name
func (*InvoiceLine) TableName() string {
	return TableNameInvoiceLine
}
