// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "Customer"

// Customer mapped from table <Customer>
type Customer struct {
	CustomerID   int32  `gorm:"column:CustomerId;primaryKey;autoIncrement:true" json:"CustomerId"`
	FirstName    string `gorm:"column:FirstName;not null" json:"FirstName"`
	LastName     string `gorm:"column:LastName;not null" json:"LastName"`
	Company      string `gorm:"column:Company" json:"Company"`
	Address      string `gorm:"column:Address" json:"Address"`
	City         string `gorm:"column:City" json:"City"`
	State        string `gorm:"column:State" json:"State"`
	Country      string `gorm:"column:Country" json:"Country"`
	PostalCode   string `gorm:"column:PostalCode" json:"PostalCode"`
	Phone        string `gorm:"column:Phone" json:"Phone"`
	Fax          string `gorm:"column:Fax" json:"Fax"`
	Email        string `gorm:"column:Email;not null" json:"Email"`
	SupportRepID int32  `gorm:"column:SupportRepId" json:"SupportRepId"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
