// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGenre = "Genre"

// Genre mapped from table <Genre>
type Genre struct {
	GenreID int32  `gorm:"column:GenreId;primaryKey;autoIncrement:true" json:"GenreId"`
	Name    string `gorm:"column:Name" json:"Name"`
}

// TableName Genre's table name
func (*Genre) TableName() string {
	return TableNameGenre
}
