// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInvoice = "Invoice"

// Invoice mapped from table <Invoice>
type Invoice struct {
	InvoiceID         int32     `gorm:"column:InvoiceId;primaryKey;autoIncrement:true" json:"InvoiceId"`
	CustomerID        int32     `gorm:"column:CustomerId;not null" json:"CustomerId"`
	InvoiceDate       time.Time `gorm:"column:InvoiceDate;not null" json:"InvoiceDate"`
	BillingAddress    string    `gorm:"column:BillingAddress" json:"BillingAddress"`
	BillingCity       string    `gorm:"column:BillingCity" json:"BillingCity"`
	BillingState      string    `gorm:"column:BillingState" json:"BillingState"`
	BillingCountry    string    `gorm:"column:BillingCountry" json:"BillingCountry"`
	BillingPostalCode string    `gorm:"column:BillingPostalCode" json:"BillingPostalCode"`
	Total             float64   `gorm:"column:Total;not null" json:"Total"`
}

// TableName Invoice's table name
func (*Invoice) TableName() string {
	return TableNameInvoice
}
