// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTrack = "Track"

// Track mapped from table <Track>
type Track struct {
	TrackID      int32   `gorm:"column:TrackId;primaryKey;autoIncrement:true" json:"TrackId"`
	Name         string  `gorm:"column:Name;not null" json:"Name"`
	AlbumID      int32   `gorm:"column:AlbumId" json:"AlbumId"`
	MediaTypeID  int32   `gorm:"column:MediaTypeId;not null" json:"MediaTypeId"`
	GenreID      int32   `gorm:"column:GenreId" json:"GenreId"`
	Composer     string  `gorm:"column:Composer" json:"Composer"`
	Milliseconds int32   `gorm:"column:Milliseconds;not null" json:"Milliseconds"`
	Bytes        int32   `gorm:"column:Bytes" json:"Bytes"`
	UnitPrice    float64 `gorm:"column:UnitPrice;not null" json:"UnitPrice"`
}

// TableName Track's table name
func (*Track) TableName() string {
	return TableNameTrack
}
